project_id = "tortracker"
[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 10000
[db]
port = 54322
shadow_port = 54320
major_version = 17
[db.seed]
enabled = true
sql_paths = ["./seed.sql"]
[studio]
enabled = false
[inbucket]
enabled = false
[storage]
enabled = true
file_size_limit = "10MiB"
[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://127.0.0.1:3000"]
enable_signup = false
[auth.email]
enable_signup = true
enable_confirmations = false
[auth.rate_limit]
sign_in_sign_ups = 1000
token_refresh = 1000
[analytics]
enabled = false
[edge_runtime]
enabled = false
